Repository hv0905/NekoImageGallery, pull requests merged in 2023-12, with the labels that each got.

#1 Add experimental OCR+BERT method to search text in images
  .gitignore
  app/Controllers/search.py
  app/Models/api_model.py
  app/Models/api_response/base.py
  app/Models/img_data.py
  app/Services/__init__.py
  app/Services/clip_service.py
  app/Services/transformers_service.py
  app/Services/vector_db_context.py
  app/config.py
  app/webapp.py
  config/default.env
  main.py
  requirements.txt
  scripts/local_indexing.py
  scripts/qdrant_create_collection.py
Labels: enhancement, Confirmed, Require Frontend Changes, breaking changes

#2 Add Easy Paddle OCR support
  .gitignore
  app/Services/__init__.py
  app/Services/ocr_services.py
  app/Services/transformers_service.py
  app/config.py
  config/default.env
  requirements.txt
  scripts/local_indexing.py
Labels: enhancement, Confirmed

#8 Allow exact match in OCR text search
  app/Controllers/search.py
  app/Models/query_params.py
  app/Services/vector_db_context.py
Labels: enhancement
