Repository hv0905/NekoImageGallery, pull requests merged in 2024-07, with the labels that each got.

#40 Refactor the lifespan part
  app/Services/index_service.py
  app/Services/lifespan_service.py
  app/Services/ocr_services.py
  app/Services/provider.py
  app/Services/storage/__init__.py
  app/Services/storage/base.py
  app/Services/storage/disabled_storage.py
  app/Services/storage/local_storage.py
  app/Services/storage/s3_compatible_storage.py
  app/Services/transformers_service.py
  app/Services/upload_service.py
  app/Services/vector_db_context.py
  app/webapp.py
  scripts/local_indexing.py
Labels: size:L

#41 Refactor local utilities and CLI interface
  .idea/NekoImageGallery.iml
  app/Controllers/admin.py
  app/Models/errors.py
  app/Services/index_service.py
  app/Services/storage/local_storage.py
  app/Services/storage/s3_compatible_storage.py
  app/Services/upload_service.py
  app/__init__.py
  app/util/local_file_utility.py
  app/webapp.py
  docker-compose-cpu.yml
  docker-compose.yml
  main.py
  readme.md
  readme_cn.md
  requirements.txt
  scripts/local_indexing.py
  scripts/local_utility.py
Labels: enhancement, size:L

#42 Add images API
  app/Controllers/images.py
  app/Models/api_models/admin_query_params.py
  app/Models/api_response/images_api_response.py
  app/Services/vector_db_context.py
  app/webapp.py
  main.py
  scripts/local_indexing.py
  tests/api/test_search.py
Labels: enhancement, size:L, test

#43 Add comments field for images and improve documentation
  app/Controllers/admin.py
  app/Models/api_models/admin_api_model.py
  app/Models/api_models/admin_query_params.py
  app/Models/api_response/images_api_response.py
  app/Models/img_data.py
  app/Models/mapped_image.py
  app/Models/search_result.py
  app/Services/index_service.py
  app/Services/upload_service.py
  app/Services/vector_db_context.py
  scripts/local_indexing.py
  tests/api/test_upload.py
Labels: documentation, enhancement, size:L
